version: '2'
services:
  postgres:
    image: postgres
    container_name: taiga-postgres
    environment:
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
  back:
    image: n4zim/taiga:back
    container_name: taiga-back
    environment:
      HOSTNAME: localhost
    links:
      - postgres
    volumes:
      - /usr/local/taiga/media
      - /usr/local/taiga/static
  front:
    image: n4zim/taiga:front
    container_name: taiga-front
    environment:
      HOSTNAME: localhost
    depends_on:
      - back
    links:
      - back:taiga-back
    volumes_from:
      - back
    ports:
      - 80:80
